[package]
name = "uroborosql-fmt-cli"
version = "0.1.0"
description = "Crate to run uroborosql-fmt on the CLI"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uroborosql-fmt = { workspace = true }
