/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function runfmt(input: string, configPath?: string | undefined | null): string
export function runfmtWithSettings(input: string, settingsJson: string, configPath?: string | undefined | null): string
