-- do nothing
INSERT INTO DISTRIBUTORS (DID, DNAME) VALUES (9, 'Antwerp Design')
ON CONFLICT (DID1, DID2, DID3) DO NOTHING;

-- on constraint name
INSERT INTO DISTRIBUTORS (DID, DNAME) VALUES (9, 'Antwerp Design')
ON CONFLICT	ON CONSTRAINT DISTRIBUTORS_PKEY	 DO NOTHING;

-- collate
INSERT INTO DISTRIBUTORS (DID, DNAME) VALUES (9, 'Antwerp Design')
ON CONFLICT	(DID1 COLLATE "x" INT4_OPS, DID2 COLLATE "x" INT4_OPS) DO NOTHING;

-- do update set where
INSERT INTO DISTRIBUTORS (DID, DNAME) VALUES (8, 'Anvil Distribution')
ON CONFLICT (DID) DO UPDATE SET DNAME = EXCLUDED.DNAME || ' (formerly ' || D.DNAME || ')' WHERE D.ZIPCODE != '21201';

-- comment after query
INSERT INTO DISTRIBUTORS (DID, DNAME) 
SELECT id FROM tbl2 WHERE id = 1 -- trailing comment
ON CONFLICT DO NOTHING;
