INSERT INTO DISTRIBUTORS (DID, DNAME) VALUES (9, 'Antwerp Design')
ON CONFLICT (DID1, DID2, DID3) DO NOTHING;

INSERT INTO DISTRIBUTORS (DID, DNAME) VALUES (9, 'Antwerp Design')
ON CONFLICT (DID1 COLLATE "x" INT4_OPS, DID2 COLLATE "x" INT4_OPS) DO NOTHING;
