SELECT
	NORMAL_FUNC(COL1	+	COL2, PARAM2)
;
SELECT
	MANY_ARGS_FUNC(PARAM1, PARAM2, PARAM3, PARAM4)
;
SELECT
	LONG_ARGS_FUNC(COL1	+	LONGLONGLONGLONGLONGLONGLONG, PARAM2)
;
SELECT
	LONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONG_FUNC(PARAM1, PARAM2, PARAM3)
;
SELECT
	FUNC1(
		CASE
			WHEN
				Z	=	1
			THEN
				FUNC3(PARAM1, PARAM2, PARAM3, PARAM4, PARAM5)
			ELSE
				FUNC2(
					CASE
						WHEN
							Z	=	1
						THEN
							'ONE'
						ELSE
							FUNC3(PARAM1, PARAM2, PARAM3, PARAM4, PARAM5)
					END
				)
		END
	)
