UPDATE
	WEATHER
SET
	(TEMP_LO, TEMP_HI, PRCP)	=	(TEMP_LO	+	1, TEMP_LO	+	15, DEFAULT)
WHERE
	CITY	=	'San Francisco'
AND	DATE	=	'2003-07-03'
;
UPDATE
	ACCOUNTS
SET
	(CONTACT_FIRST_NAME, CONTACT_LAST_NAME)	=	(
		SELECT
			FIRST_NAME	AS	FIRST_NAME
		,	LAST_NAME	AS	LAST_NAME
		FROM
			SALESMEN
		WHERE
			SALESMEN.ID	=	ACCOUNTS.SALES_ID
	)
;
