CREATE SCHEMA app;
CREATE TABLE public.users (id integer, name text, age integer);
CREATE TABLE app.users (app_id integer);
CREATE TABLE public.only_public (id integer);
CREATE VIEW app.shadowed_view AS SELECT 1 AS id;
CREATE TABLE public.shadowed_view (id integer);
CREATE TABLE public."Users" ("Id" integer);
CREATE TABLE public.dropped (first_col integer, removed integer, last_col integer);
ALTER TABLE public.dropped DROP COLUMN removed;
CREATE TABLE public.zero_columns ();
CREATE TABLE public.partitioned (id integer) PARTITION BY RANGE (id);
CREATE VIEW public.user_view AS SELECT id FROM public.users;
CREATE SEQUENCE public.user_sequence;
CREATE SCHEMA hidden;
CREATE TABLE hidden.users (secret_id integer);
CREATE SCHEMA "PG_TEMP";
CREATE TABLE "PG_TEMP".users (quoted_id integer);
CREATE SCHEMA pg_temp_data;
CREATE ROLE catalog_reader LOGIN;
GRANT USAGE ON SCHEMA public, app, "PG_TEMP", pg_temp_data TO catalog_reader;
ALTER ROLE catalog_reader SET search_path = app, public;
